---
title: "coronavirus-wrangle.Rmd"
output: github_document
---

library(tidyverse) ##install.packages("tidyverse")

# read in corona .csv #
coronavirus <- read_csv('https://raw.githubusercontent.com/RamiKrispin/coronavirus-csv/master/coronavirus_dataset.csv', col_types = cols(Province.State = col_character()))

## explore the coronavirus dataset
coronavirus # this is super long! Let's inspect in different ways  

head(coronavirus) # shows first 6  
tail(coronavirus) # shows last 6  
head(coronavirus, 10) # shows first X that you indicate  
tail(coronavirus, 12) # guess what this does!  

#Learning basic info on the data.frame
names(coronavirus)  
dim(coronavirus)    # ?dim dimension  
ncol(coronavirus)   # ?ncol number of columns  
nrow(coronavirus)   # ?nrow number of rows  

# Statistical overview of data.frame
summary(coronavirus)  

# Skimr
## If we don't already have skimr installed, we will need to install it
install.packages('skimr')  
library(skimr)  
skim(coronavirus)  

# Look at variables inside the data.frame
## Use $ to extract a single variable
coronavirus$cases # very long! hard to make sense of...  

head(coronavirus$cases) # can do the same tests we tried before  

str(coronavirus$cases) # it is a single numeric vector  

summary(coronavirus$cases) # same information, formatted slightly differently  

# dplyr basics
## 5 common functions
1. filter()
  + pick observations by their values
2. select()
  + pick variables by their names
3. mutate()
  + create new variables with functions of existing variables
4. arrange()
  + reorder the rows
5. summarise()
  + collapse many values down to a single summary




# filter() subsets data row-wise (observations)
## filter() is a function in dplyr that takes logical expressions and returns the rows for which all are TRUE.
filter(coronavirus, cases > 0)  

### Records for the US only
filter(coronavirus, Country.Region == "US")  

coronavirus_us <- filter(coronavirus, Country.Region == "US")  

### Records for both the US and Canada
filter(coronavirus, Country.Region == "US" | Country.Region == "Canada")  

###### Shorthand
filter(coronavirus, Country.Region %in% c("US", "Canada"))  

### Death count in the US
###### We can use either of these notations:
filter(coronavirus, Country.Region == "US", type == "death")  
filter(coronavirus, Country.Region == "US" & type == "death")  

## Total number of deaths in the US in the data.frame time region
x <- filter(coronavirus, Country.Region == "US", type == "death")  
sum(x$cases)  





# select() subsets data column-wise (variables)
## We can select multiple columns with a comma, after we specify the data frame (coronavirus).
select(coronavirus, date, Country.Region, type, cases)  

## can also use - to deselect columns
select(coronavirus, -Lat, -Long) # you can use - to deselect columns   



# Use select() and filter() together
#### Combine and filter data to retain only records for the US and remove the Lat, Long and Province.State columns. We will save this as a subsetted variable  

coronavirus_us  <- filter(coronavirus, Country.Region == "US")  
coronavirus_us2 <- select(coronavirus_us, -Lat, -Long, -Province.State)  


# Pipe operator %>% 
##### Equivalent to head(coronavirus)  

coronavirus %>% head()  

##### Can still specify other arguments to this function  
###### First 3 rows of data

coronavirus %>% head(3)

## Think "and then" when you see %>%   

### instead of this...  
coronavirus_us  <- filter(coronavirus, Country.Region == "US")  
coronavirus_us2 <- select(coronavirus_us, -Lat, -Long, -Province.State)   
### ...we can do this  
coronavirus_us  <- coronavirus %>% filter(Country.Region == "US")  
coronavirus_us2 <- coronavirus_us %>% select(-Lat, -Long, -Province.State)

## We can use the pipe to chain these 2 operations together  

coronavirus_us  <- coronavirus %>% 
  filter(Country.Region == "US") %>%
  select(-Lat, -Long, -Province.State)     
  
# mutate() adds new variables
### Useful to add new columns that are functions of existing columns

## Rearranging the data set to make it easier to mutate  

coronavirus_ttd <- coronavirus %>% 
  select(country = Country.Region, type, cases) %>%
  group_by(country, type) %>%
  summarise(total_cases = sum(cases)) %>%
  pivot_wider(names_from = type,
              values_from = total_cases) %>%
  arrange(-confirmed)
  
## Let's have a look at the structure of that new rearranged dataset  
coronavirus_ttd  


## Comparing the total death count to confirmed cases by country by dividing death/confirmed  

coronavirus_ttd %>%
  mutate(deathrate = death / confirmed)   

#### We can modify the mutate equation in many ways. For example, if we want to adjust the number of significant digits printed, we can type:  
coronavirus_ttd %>%
  mutate(deathrate = round(death / confirmed, 2))  
  
## Create a new variavble that shows proportion of confirmed cases for which the outcome is unknown  

coronavirus_ttd %>%
  mutate(unknown_outcome = confirmed-death-recovered/ confirmed) %>% 
  filter(confirmed < 20000)  


